### ISSUE TITLE
Take into account missed events

### ISSUE THREAD

**Issue by aspiers** [dhellmann/openstack-summit-counter#3]
I've been to every summit since San Francisco, *except* Hong Kong. 
 So the tool should allow me to specify which one I missed, so that I don't have to take the result of `openstack summit count folsom` and then spend extra effort subtracting 1 in my head.  Clearly it's even important for people who have missed multiple summits, although maybe the less loyal haven't earned the right to use this tool anyway.

**Comment by aspiers** [comment]
Suggested usage, avoiding the need for a persistent backend:

    $ openstack summit count --missed=icehouse folsom
    +---------+-------+
    | Field   | Value |
    +---------+-------+
    | Summits | 14    |
    +---------+-------+

or with a backend:

    $ openstack summit first folsom
    +--------+----------+---------------+--------------------------------------------------------+
    | Number | Name     | Location      | URL                                                    |
    +--------+----------+---------------+--------------------------------------------------------+
    |      6 | Folsom   | San Francisco | https://wiki.openstack.org/wiki/Design_Summit/Folsom   |
    +--------+----------+---------------+--------------------------------------------------------+
    $ openstack summit count
    +---------+-------+
    | Field   | Value |
    +---------+-------+
    | Summits | 15    |
    +---------+-------+
    $ openstack summit missed
    No summits missed
    $ openstack summit missed icehouse
    +--------+----------+---------------+--------------------------------------------------------+
    | Number | Name     | Location      | URL                                                    |
    +--------+----------+---------------+--------------------------------------------------------+
    |      9 | Icehouse | Hong Kong     | https://wiki.openstack.org/wiki/Design_Summit/Icehouse |
    +--------+----------+---------------+--------------------------------------------------------+
    $ openstack summit missed
    +--------+----------+---------------+--------------------------------------------------------+
    | Number | Name     | Location      | URL                                                    |
    +--------+----------+---------------+--------------------------------------------------------+
    |      9 | Icehouse | Hong Kong     | https://wiki.openstack.org/wiki/Design_Summit/Icehouse |
    +--------+----------+---------------+--------------------------------------------------------+
    $ openstack summit count
    +---------+-------+
    | Field   | Value |
    +---------+-------+
    | Summits | 14    |
    +---------+-------+
    $ openstack summit missed icehouse
    +--------+----------+---------------+--------------------------------------------------------+
    | Number | Name     | Location      | URL                                                    |
    +--------+----------+---------------+--------------------------------------------------------+
    |      9 | Icehouse | Hong Kong     | https://wiki.openstack.org/wiki/Design_Summit/Icehouse |
    |     14 | Newton   | Austin        | https://wiki.openstack.org/wiki/Design_Summit/Newton   |
    +--------+----------+---------------+--------------------------------------------------------+
    $ openstack summit count
    +---------+-------+
    | Field   | Value |
    +---------+-------+
    | Summits | 13    |
    +---------+-------+

**Comment by dhellmann** [comment]
The official home for the code for this is now https://opendev.org/x/osc-summit-counter and the bug/feature tracker is https://storyboard.openstack.org/#!/project/1100

I have added you to the reviewer group for that repo in gerrit.
